### ISSUE TITLE
Add pretty print option

### ISSUE THREAD

**Issue by eriksson-daniel** [hermith/haikubot#7]
Export to haikus.txt with the contents looking like this:

```
Haiku haiku hai
ku haiku haiku haiku
Haiku haiku hai

One Two Three Four Five
Six Seven Eight Nine Ten El
even Twelve Thirteen

...
```

**Comment by karl-run** [comment]
Done. :+1:

**Comment by karl-run** [comment]
Export is cut off when there's a lot of haikus, I believe this is because of the RTM APIs limits, this needs to be fixed.

**Comment by karl-run** [comment]
This is fixed now, a configurable parameter has been added to config.py. 100 haikus seem to fit nicely into a single snippet.
